### ISSUE TITLE
Should uuid.Nil marshal to null instead of all zeroes

### ISSUE THREAD

**Issue by maroux** [google/uuid#119] opened 2023-08-04 22:24 UTC
The library uses the `uuid.Nil` value as an [empty value](https://github.com/google/uuid/blob/44b5fee7c49cf3bcdf723f106b36d56ef13ccc88/uuid.go#L73). This suggests to me that Nil value is treated as a special value, which is in line with the [RFC](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.7). However, the behavior of this value when marshaling to json is questionable. The library serializes to `00000000-0000-0000-0000-000000000000` ([play](https://go.dev/play/p/USjZes8HzNg)) instead of `null`. Should this behavior be changed? Marshaling to text can probably yield an error, or just empty string, not sure.

**Comment by petkostas** [comment] 2023-10-27 13:30
I ran into some problems while using UUID with the echo framework, which caused me a lot of inconvenience. I would be grateful if there is a solution available for this issue. Moreover, this problem results in an extra burden of validations that need to be implemented.

```golang
TestResultDTO struct {
	ConsumerId uuid.UUID `json:"consumer_id,omitempty"`
}
```

```golang
func (h *Handler) TestRun(c echo.Context) error {
	var testResultDTO models.TestResultDTO
	err := c.Bind(&testResultDTO)
	if err != nil {
		return err
	}
	jsonString, err := json.Marshal(testResultDTO)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(jsonString))
	return c.JSON(http.StatusCreated, testResultDTO)
}
```
Sending a POST request to the test endpoint:
```shell
curl --request POST \
  --url http://localhost:xxxx/test \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: foo' \
  --data '{}'
```

```json
{
	"consumer_id": "00000000-0000-0000-0000-000000000000"
}
```
Which in this case is undesirable

**Comment by mazar** [comment] 2024-03-25 22:26
I'm interested in a solution for this as well.

**Comment by Mirko607** [comment] 2024-06-19 06:51
Who else would like to marshal `uuid.Nil` to json `null`? Give a 👍

**Comment by pborman** [comment] 2024-06-19 21:04
What you want is `uuid.NullUUID` which is like a `UUID` but it can be null (at the cost of additional data).

uuid.Nil has a specific definition and it is not null.  From [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.7):

```
[4.1.7]  Nil UUID

   The nil UUID is special form of UUID that is specified to have all
   128 bits set to zero. 
```

I am going to close this issue since `uuid.NullUUID` has the behavior you want.

**Closed by pborman** 2024-06-19 21:04 UTC

**Comment by F21** [comment] 2025-01-13 04:48
I tired using `NullUUID`, but the problem is that it sets the value to the string `null` if there is no UUID set, so the  `omitempty` json struct tag doesn't work correctly.

See: https://github.com/google/uuid/blob/v1.6.0/null.go#L106

**Comment by gogbog** [comment] 2025-02-10 23:09
This is still an issue for me. **NullUUID** is not the expected behavior. If the request payload doesn't include the field, I expect omitempty to exclude it from the JSON output.

**Comment by tisonkun** [comment] 2025-03-04 12:38
I have to use `` StatementId *uuid.UUID `json:"statement_id,omitempty"` `` now at https://github.com/scopedb/scopedb-sdk/pull/44

**Comment by gogbog** [comment] 2025-03-04 13:06
> I have to use `` StatementId *uuid.UUID `json:"statement_id,omitempty"` `` now at [scopedb/scopedb-sdk#44](https://github.com/scopedb/scopedb-sdk/pull/44)

Yeah at the end, I made it work that way. The pointer can be nil, but an object cannot. This is the only solution that worked for me as well.
